bleff/bleff/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('menu.urls')),
    path("game/", include("game.urls")),
    path('users/', include('users.urls')),
    path("admin/", admin.site.urls),
]

bleff/game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("enter/", views.enter_game, name="enter_game"),
    path("create/", views.create_game, name="create"),
    path("<int:game_id>/", views.waiting, name="waiting"),
    path("start/<int:game_id>/", views.start_game, name="start_game"),
    path("<int:game_id>/hand/", views.hand_view, name="hand"),
    path("<int:game_id>/hand/choose/", views.choose_word, name="choose"),
    path("<int:game_id>/hand/guess/", views.make_guess, name="make_guess"),
    path("<int:game_id>/hand/guesses/check", views.check_guesses, name="check_guesses"),
    path("<int:game_id>/hand/guesses/", views.guesses_view, name="guesses"),
    path("<int:game_id>/hand/guess/vote", views.vote, name="vote"),
    path("hand/<int:hand_id>/", views.hand_detail, name="hand_detail"),
]

bleff/game/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_POST, require_GET
from django.db.models import Model
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from .models import Game, HandGuess, Language, Meaning, Play, Hand, Vote, Word, Guess, ConditionTag, Condition
from .utils import (
    plays_game,
    get_game_hand,
    get_hand_choice_words,
    remove_fields,
    conditions_are_met,
    is_leader,
    votes_remaining,
    already_vote,
    last_hand,
    points_in_game,
    get_game_users,
    guessed_right,
    game_finished
)
from .decorators import play_required, leader_required, conditions_met

def handle_redirection(request):
    # If does not exists a Play with this user and a game unfinished.
    is_playing_something = Play.objects.filter(user=request.user).exclude(game__finished_at__isnull=False)
    if not is_playing_something:
        return redirect('game:index')

    # If exists a game, but does not met the conditions.
    game = is_playing_something[0].game
    if len(conditions_are_met(game_id=game.id)) > 0:
        # TODO: If the game has already a hand unfinished, an infinte loop appears. 
        return redirect('game:waiting', game_id=game.id)

    # If exists a game, but does not start yet.
    game_start = Hand.objects.filter(game=game).exists()
    if not game_start:
        return redirect('game:waiting', game_id=game.id)

    # If the game exists and there is no current hand, then the user should go to detail.
    hand = get_game_hand(game_id=game.id)
    if not hand:
        return HttpResponseRedirect(reverse("game:hand_detail", args=(last_hand(game_id=game.id).id,)))

    # If the game started, and the user doesn't create a guess yet.
    already_made_guess = Guess.objects.filter(hand=hand, writer=request.user).exists()
    if not already_made_guess:
        return HttpResponseRedirect(reverse("game:hand", args=(game.id,)))
  
    # If the guess was already made and you are the leader, then you must check.
    is_leader_var = is_leader(request.user, game_id=game.id)
    if is_leader_var and HandGuess.objects.filter(is_correct=None).exists():
        return HttpResponseRedirect(reverse("game:check_guesses", args=(game.id,)))


    # If the guess was already made and you are not the leader, or leader already checked. BUT YOU DON'T GUESSED RIGHT!
    if not is_leader_var and not already_vote(user=request.user, game_id=game.id) and not guessed_right(user=request.user, hand=hand):
        return HttpResponseRedirect(reverse("game:guesses", args=(game.id,)))

    # If you already vote, then go to the end.
    return HttpResponseRedirect(reverse("game:hand_detail", args=(hand.id,)))


def create_or_none(model: Model, fields):
    try:
        creation = model.objects.create(**fields)
        creation.full_clean()
        return creation
    except Exception as e:
        # TODO: message error
        print(e)
        return None


def update_or_none(model: Model):
    try:
        model.save()
        model.full_clean()
    except Exception as e:
        # TODO: message error
        print(e)
        return None


def ws_event(data, game_id):
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        f'game_{game_id}',
        data
    )


class IndexView(generic.ListView):
    model = Game
    template_name = "game/index.html"


    def get_queryset(self, **kwargs):
        return Game.objects.filter(finished_at__isnull=True)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['languages'] = Language.objects.all()

        context['conditions'] = [(c.tag, range(c.min, c.max + 1)) for c in ConditionTag.objects.all()]

        return context


@login_required
@require_GET
@play_required(handle_redirection)
def waiting(request, game_id):
    game = get_object_or_404(Game, id=game_id)
    conditions = Condition.objects.filter(game=game)
    users = [p.user.username for p in Play.objects.filter(game=game_id)]

    ws_event({
        'player_username': request.user.username,
        'type': 'player_join'
    }, game_id)    

    return render(
        request, 
        'game/waiting.html', 
        {
            'users': users, 
            'conditions': conditions, 
            "game_id": game_id,
            'game': game
        }
    )


@login_required
@require_POST
def enter_game(request):
    key = 'game'
    if not key in request.POST:
        return handle_redirection(request=request)

    game_id = request.POST[key]
    game = Game.objects.get(id=game_id)

    if plays_game(user=request.user, game_id=game_id):
        return handle_redirection(request=request)
    
    try:
        Play.objects.create(game=game, user=request.user)
    except Exception as e:
        # TODO: message error
        print(e)
        return handle_redirection(request=request)

    return redirect('game:waiting', game_id=game.id)


@login_required
@require_POST
def create_game(request):
    language_tag = request.POST['language']
    language = get_object_or_404(Language, tag=language_tag)

    game = create_or_none(model=Game, fields={'creator': request.user, 'idiom': language})

    if game:
        condition_tags = ConditionTag.objects.all()

        copy = request.POST.copy()

        # TODO: This should work now, but it's not the best solution.
        if copy['MAX_PLAYERS'] < copy['MIN_PLAYERS']:
            copy['MAX_PLAYERS'] = copy['MIN_PLAYERS']

        for tag in condition_tags:
            if tag.tag in copy:
                create_or_none(model=Condition, fields={'game': game, 'tag': tag, 'value': int(copy[tag.tag])})

    return redirect('game:waiting', game_id=game.id) if game else handle_redirection(request=request)


@login_required
@require_POST
@play_required(handle_redirection)
@conditions_met(handle_redirection)
def start_game(request, game_id):
    game = Game.objects.get(pk=game_id)

    # Creates hand if there is no game-hand and the player is the creator
    start_hand = create_or_none(model=Hand, fields={'game': game}) if not game.creator or request.user == game.creator else None

    # TODO: This sends an event that affects the creator too...
    if start_hand:
        ws_event({'type': 'start_game'}, game_id)

    return HttpResponseRedirect(reverse("game:hand", args=(game_id,))) if start_hand else handle_redirection(request=request)


@login_required
@play_required(handle_redirection)
@conditions_met(handle_redirection)
def hand_view(request, game_id):
    hand = get_game_hand(game_id)
    words = []
    word = ''
    
    if request.user.id == hand.leader.id and not hand.word:
        words = [Meaning.objects.get(word=w, language=hand.game.idiom) for w in get_hand_choice_words(hand=hand)]
    elif hand.word:
        word = Meaning.objects.get(word=hand.word, language=hand.game.idiom).word_translation

    return render(request, 'game/hand.html', {"hand": hand, "words_to_choose": words, "game_id": game_id, "game": hand.game, "word": word })


@login_required
@require_POST
@play_required(handle_redirection)
@leader_required(handle_redirection)
@conditions_met(handle_redirection)
def choose_word(request, game_id):
    choice = request.POST['choice']

    # If the chosen word does not exists.
    if not Word.objects.filter(word=choice).exists():
        return handle_redirection(request=request)
    
    hand = get_game_hand(game_id=game_id)
    try:
        hand.word = Word.objects.get(word=choice)
        hand.save()
    except Exception as e:
        # TODO: message error
        print(e)
        return handle_redirection(request=request)

    ws_event({'type': 'chosen_word'}, game_id)
    
    return HttpResponseRedirect(reverse("game:hand", args=(game_id,)))


@login_required
@require_POST
@play_required(handle_redirection)
@conditions_met(handle_redirection)
def make_guess(request, game_id):
    guess = request.POST['guess']
    hand = get_game_hand(game_id=game_id)

    guess_created = create_or_none(model=Guess, fields={'hand': hand, 'writer':request.user, 'content': guess})

    if guess_created and request.user.id == hand.leader.id:
        return HttpResponseRedirect(reverse("game:check_guesses", args=(game_id,)))
    

    if (guess_created):
        ws_event({
            'type': 'new_guess',
            'new_guess': {
                'content': guess,
                'id': guess_created.id,
                'word': hand.word.word
            }
        }, game_id)

    return HttpResponseRedirect(reverse("game:guesses", args=(game_id,))) if guess_created else handle_redirection(request=request)


@login_required
@require_GET
@play_required(handle_redirection)
@conditions_met(handle_redirection)
def guesses_view(request, game_id):
    if is_leader(user=request.user, game_id=game_id):
        return HttpResponseRedirect(reverse("game:check_guesses", args=(game_id,)))
    elif already_vote(user=request.user, game_id=game_id):
        return handle_redirection(request=request)

    template_name = "game/guesses.html"
    hand = get_game_hand(game_id=game_id)

    guesses_ready = not HandGuess.objects.filter(hand=hand, is_correct=None).exists()

    hand_guesses = remove_fields(object=HandGuess, fields=['writer'], filters={'hand': get_game_hand(game_id=game_id), 'is_correct': False})

    guesses = [Guess.objects.get(pk=hg.guess_id) for hg in hand_guesses] if guesses_ready else []

    context = {
        'hand': hand,
        'game_id': game_id,
        'guesses': guesses
    }
        
    return render(request=request, template_name=template_name, context=context)
    

@login_required

bleff/game/templates/game/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bleff</title>
    <script type="text/javascript">
        const gameId= '{{ game_id }}'
        const USERNAME = '{{ user.username }}'
    </script>
    <script src="{% static 'game/js/WebSocketManager.js' %}" type="module"></script>
    <script src="{% static 'game/js/WebSocketSetup.js' %}" type="module"></script>
    <link rel="stylesheet" href="{% static 'bleff/css/styles.css' %}">
</head>
<body>
    <main class="main_container">
        {% block content %}{% endblock %}
    </main>
</body>
</html>

bleff/game/templates/game/check_guesses.html
{% extends 'game/base.html' %}

{% block content %}
    <div class="container" data-template="check">
        <form action="{% url 'game:check_guesses' game_id %}" method="post" class="main_container">
            {% csrf_token %}
            <fieldset>
                <legend><h2>Check guesses</h2></legend>
                <div id="guesses_to_check">
                    {% for guess in guesses %}
                        <fieldset>
                            <legend>{{ hand.word.word }} means:</legend>
                            <label>{{ guess.content }}</label>
                            <select id="{{guess.id}}" name="{{guess.id}}">
                                <option value="False">Ok</option>
                                <option value="True">Remove</option>
                            </select>
                        </fieldset>
                    {% endfor %}
                </div>
            </fieldset>
            <input class="button" type="submit" value="Ready" id="checked">
        </form>
    </div>
{% endblock %}

bleff/game/templates/game/guesses.html
{% extends 'game/base.html' %}

{% block content %}
    <div class="container" data-template="guesses">
        {% if guesses %}
            <form action="{% url 'game:vote' game_id %}" method="post" class="main_container">
                {% csrf_token %}
                <fieldset>
                    <legend><h2>Vote a guess</h2></legend>
                    {% for guess in guesses %}
                        <div class="pointer">
                            <input type="radio" name="guess" id="{{ guess.id }}" value="{{ guess.id }}">
                            <label>{{ hand.word.word }} means: {{ guess.content }}</label>
                        </div>
                    {% endfor %}
                </fieldset>
                <input class="button" type="submit" value="Vote">
            </form>
        {% else %}
            <div>Waiting for other guesses</div>
        {% endif %}
    </div>
{% endblock %}

bleff/game/templates/game/hand.html
{% extends 'game/base.html' %}

{% block content %}
    <div class="container" data-template="hand">
        {% if words_to_choose %}
            <form action="{% url 'game:choose' hand.game.id %}" method="post" class="main_container">
                {% csrf_token %}
                <fieldset>
                    {% for choice in words_to_choose %}
                        <div class="pointer">
                            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.word }}">
                            <label>{{choice}}</label>
                        </div>
                    {% endfor %}
                </fieldset>
                <input class="button" id="choose" type="submit" value="Choose">
            </form>
        {% elif not hand.word %}
            <div>Waiting {{hand.leader}} to choose a word</div>
        {% else %}
            <form action="{% url 'game:make_guess' hand.game.id %}" method="post" class="main_container">
                {% csrf_token %}
                <fieldset>
                    <legend><h2>Write your guess for '{{word}}':</h2></legend>
                    <textarea name="guess" id="guess" rows="10" cols="100"></textarea>
                </fieldset>
                <input class="button" id="send_guess" type="submit" value="Submit">
            </form>
        {% endif %}
    </div>
{% endblock %}

bleff/game/templates/game/hand_detail.html
{% extends 'game/base.html' %}

{% block content %}
    <div class="container" data-template="hand_detail">
        <h1>Hand: {{ hand.word }} {{gameId}}</h1>
        <fieldset id="votes">
            {% for vote in votes %}
                <div>
                    <label>~ Vote '{{ vote.to.guess.content }}' from {{ vote.user }}</label>
                </div>
            {% endfor %}
        </fieldset>
        <hr>
        {% if hand.finished_at %}
            <fieldset>
                {% for guess in guesses %}
                    <div>
                        <label>{{ word }} guess: '{{ guess.content }}' by {{ guess.writer }}. Votes: {{ guess.votes }}</label>
                    </div>
                {% endfor %}
            </fieldset>
        {% endif %}
        <hr>
            <fieldset>
                <legend>Points</legend>
                {% for point in points %}
                    <div>
                        <label>{{ point.user }}: {{ point.value }}pts</label>
                    </div>
                {% endfor %}
            </fieldset>
        <hr>
        {% if hand.game.finished_at %}
            <form action="{% url 'game:index' %}" method="get">
                {% csrf_token %}
                <input class="button" type="submit" value="Return">
            </form>
        {% elif not hand.game.creator or hand.game.creator.id == user.id %}
            <form action="{% url 'game:start_game' hand.game.id %}" method="post">
                {% csrf_token %}
                <input class="button" type="submit" value="Next Hand">
            </form>
        {% endif %}
    </div>
{% endblock %}

bleff/game/templates/game/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bleff</title>
    <link rel="stylesheet" href="{% static 'bleff/css/styles.css' %}">
</head>
<body>
    <form action="{% url 'game:create' %}" method="post" class="main_container">
        {% csrf_token %}
        <fieldset class="row_container">
            <legend><h2>Create a Game</h2></legend>
                
                <div class="pointer">
                    <label for="language">Language: </label>
                    <select id="language" name="language">
                        {% for language in languages %}
                            <option value={{language.tag}}>{{language.name}}</option>
                        {% endfor %}
                    </select>
                </div>

                {% for condition, values in conditions %}
                    <div class="pointer">
                        <label for={{condition}}>{{condition}} </label>
                        <select id={{condition}} name={{condition}}>
                                {% for i in values%}
                                    <option value={{i}}>{{i}}</option>
                                {% endfor %}
                        </select>
                    </div>
                {% endfor %}
        </fieldset>
        <input class="button" type="submit" value="Create">
    </form>
    
    <form action="{% url 'game:enter_game' %}" method="post" class="main_container">
        {% csrf_token %}
        {% if object_list %}
            <fieldset>
                {% for game in object_list %}
                    <div class="pointer">
                        <input type="radio" name="game" id="game{{ forloop.counter }}" value="{{ game.id }}">
                        <label>Game {{game.id}} ~ Created by: {{game.creator}}</label>
                    </div>
                {% endfor %}
            </fieldset>
            <input class="button" type="submit" value="Enter">
        {% else %}
            <fieldset>
                <div>No games are available.</div>
            </fieldset>
        {% endif %}
    </form>
</body>
</html>

bleff/game/templates/game/waiting.html
{% extends 'game/base.html' %}

{% block content %}
    <div class="container" data-template="waiting"> 
        <form action="{% url 'game:start_game' game_id %}" method="post" class="main_container">
            {% csrf_token %}
            <fieldset>
                <legend><h2>Waiting List</h2></legend>
                <ul id="usernames">
                    {% for user in users %}
                        <li id="{{user}}"><h1>{{user}}</h1></li>
                    {% endfor %}
                </ul>
            </fieldset>
            
            {% if not game.creator or game.creator.id == user.id %}
                <input class="button" id="start_game" type="submit" value="Start Game">
            {% endif %}
        </form>
        
        <div>Players Count: {{object_list|length}}</div>
        {% for condition in conditions %}
            <div>{{condition.tag}}: {{condition.value}}</div>
        {% endfor %}
    </div>
{% endblock %}