bleff/bleff/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('menu.urls')),
    path("game/", include("game.urls")),
    path('users/', include('users.urls')),
    path("admin/", admin.site.urls),
]

bleff/game/urls.py
from django.urls import path

from . import views

app_name = "game"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("enter/", views.enter_game, name="enter_game"),
    path("create/", views.create_game, name="create"),
    path("<int:game_id>/", views.waiting, name="waiting"),
    path("start/<int:game_id>/", views.start_game, name="start_game"),
    path("<int:game_id>/hand/", views.hand_view, name="hand"),
    path("<int:game_id>/hand/choose/", views.choose_word, name="choose"),
    path("<int:game_id>/hand/guess/", views.make_guess, name="make_guess"),
    path("<int:game_id>/hand/guesses/check", views.check_guesses, name="check_guesses"),
    path("<int:game_id>/hand/guesses/", views.guesses_view, name="guesses"),
    path("<int:game_id>/hand/guess/vote", views.vote, name="vote"),
    path("hand/<int:hand_id>/", views.hand_detail, name="hand_detail"),
]

bleff/menu/urls.py
from django.urls import path

from . import views

app_name = "menu"

urlpatterns = [
    path("", views.main, name="main"),
]

bleff/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("signup/", views.signup_view, name="signup"),
    path("logout", views.logout_view, name='logout')
]

bleff/menu/models.py
from django.db import models

# Create your models here.

bleff/menu/views.py
from django.shortcuts import render
from django.views.decorators.http import require_GET

@require_GET
def main(request):
    return render(request=request, template_name='menu/main_menu.html')

bleff/menu/templates/menu/main_menu.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main Menu</title>
    <link rel="stylesheet" href="{% static 'bleff/css/styles.css' %}">
</head>
<body>
    <form action="" method="get" class="main_container" id="redirectForm">
        <fieldset>
            <legend><h2>Main Menu</h2></legend>
            <div class="pointer" onclick="selectOption('login')">
                <input type="radio" name="redirect" id="login" value="{% url 'users:login' %}">
                <label for="login">Log In</label>
            </div>
            <div class="pointer" onclick="selectOption('signup')">
                <input type="radio" name="redirect" id="signup" value="{% url 'users:signup' %}">
                <label for="signup">Sign Up</label>
            </div>
            <div class="pointer" onclick="selectOption('play')">
                <input type="radio" name="redirect" id="play" value="{% url 'game:index' %}">
                <label for="play">Play</label>
            </div>
        </fieldset>
        <input class="button" type="submit" value="Go">
    </form>
    <script>
        // TODO: Move this to a single JS file so that it can be imported and reused in any template.
        function selectOption(inputId) {
            document.querySelectorAll('input[name="redirect"]').forEach(function(input) {
                input.checked = false;
            });
        
            document.getElementById(inputId).checked = true;
        }
        document.getElementById('redirectForm').addEventListener('submit', function(event) {
            event.preventDefault();
            const selectedUrl = document.querySelector('input[name="redirect"]:checked')?.value;
            if (selectedUrl) {
                window.location.href = selectedUrl;
            } else {
                alert('Please select an option.');
            }
        });
    </script>
</body>
</html>